name: npc_mobile_flutter
description: Cross-platform mobile app for browsing and displaying product information.

# Specify the location to publish the package. 'none' means it won't be published to pub.dev.
publish_to: 'none'

# The version number of the Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  #For accessing environment variables
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting rules for maintaining code quality.
  flutter_lints: ^2.0.0

  #For changing app package name
  change_app_package_name: ^1.1.0 # dart run change_app_package_name:main com.etdvlpr.npc_mobile_flutter

  #For changing app icon
  flutter_launcher_icons: ^0.13.1 # dart run flutter_launcher_icons

  #For creating splash screen
  flutter_native_splash: ^2.3.2 # dart run flutter_native_splash:create

# Flutter specific configuration.
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash.png

  android_12:
    image: assets/images/12/splash.png
    color: "#ffffff"
    icon_background_color: "#ffffff"

  android: true
  ios: true

  android_gravity: center
  ios_content_mode: center

  fullscreen: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
